# Generated by Django 4.2.6 on 2024-06-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choices',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='questions',
        ),
    ]
