# Generated by Django 4.2.6 on 2024-06-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_rename_choice_text_choice_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choices',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.CharField(max_length=500),
        ),
    ]
