# Generated by Django 4.2.6 on 2024-06-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_alter_choice_choices_alter_question_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choices',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='question_text',
        ),
    ]
